<a href="https://colab.research.google.com/github/Saimanasa25/PyTorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Tensors**
### What are tensors?
A tensor is a way to store numbers in one or more dimensions.\
\
A single number is a 0D tensor\
Example: 5\
\
A list of numbers is a 1D tensor, also called a vector\
Example: [2, 4, 6]\
\
table of numbers is a 2D tensor, also called a matrix\
Example:\
[1 2]\
[3 4]\
\
Images and videos use higher dimensional tensors.\
A color image can be stored as:\
Height × Width × Color channels\
For example, \
1080 × 1920 × 3.


In [7]:
import torch
import numpy as np

In [8]:
# list
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
print(my_list)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [9]:
# numpy array
np1 = np.random.rand(3,4)
print(np1)

[[0.16314517 0.61156988 0.53577128 0.63188479]
 [0.85600753 0.86976672 0.58426401 0.42278732]
 [0.800211   0.52332633 0.7672573  0.49693086]]


In [11]:
#tensor
tensor_2d = torch.randn(3,4)
print(tensor_2d)


tensor([[ 0.4154,  0.8536, -1.0023,  0.2818],
        [ 1.0328, -1.8590,  0.9526,  1.7873],
        [ 2.5891, -0.3513,  1.4754, -0.2336]])


In [13]:
my_tensor = torch.tensor(np1)
print(my_tensor)


tensor([[0.1631, 0.6116, 0.5358, 0.6319],
        [0.8560, 0.8698, 0.5843, 0.4228],
        [0.8002, 0.5233, 0.7673, 0.4969]], dtype=torch.float64)
